version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: "Friday"
    open-pull-requests-limit: 10
    groups:
      maven-patch-group:
        update-types:
        - "patch"
